// Regression logic và DOM giả lập; không thay kiểm tra trình duyệt thật.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const path=require('node:path'),root=path.join(__dirname,'..');
const memory=new Map();
const c={window:{},localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)},Date,Math,JSON};
c.window=c;vm.createContext(c);
for(const file of ['js/data.js','js/store.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c);
c.Store.load();
const before=JSON.stringify(c.Store.get());
assert.throws(()=>c.Store.review('u-lead','v-moc-3','invalid','Lý do đủ dài'));
assert.equal(JSON.stringify(c.Store.get()),before,'Invalid action must not alter data');
const nodes=new Map();const $=s=>{if(!nodes.has(s))nodes.set(s,{innerHTML:'',checked:false});return nodes.get(s)};
const version=(id,projectId,status)=>({id,projectId,status,name:id,author:'u',history:[],checkBrand:false,checkInfo:false});
let rerender,modal;
const A={data:{versions:[version('old','p','Approved'),version('pending','p','Internal Review'),version('other','q','Internal Review')],notes:[],users:[]},project:{id:'p',name:'Project P'},user:{id:'u-lead'},preserveFocus:fn=>fn(),header:()=>'',banner:()=>'',empty:()=>'',esc:s=>String(s??''),icon:()=>'',textField:()=>'',modal:(title,body,submit)=>modal={title,body,submit},toast:()=>{},init:(key,fn)=>{rerender=fn;fn()},$, $$:()=>[]};
let reviewed;
const page={App:A,Store:{review:(...args)=>reviewed=args}};vm.createContext(page);
vm.runInContext(fs.readFileSync(path.join(root,'js/pages/lead-internal-review.js'),'utf8'),page);
assert.match($('#main').innerHTML,/value="pending" selected/,'Prefer pending review over first approved version');
assert(!$('#main').innerHTML.includes('value="other"'),'Selector scoped to current project');
$('#rework').onclick();modal.submit({reason:'Thay đổi màu nhãn'});assert.equal(reviewed[1],'pending');
$('#review-version').onchange({target:{value:'old'}});
assert.match($('#main').innerHTML,/value="old" selected/);
assert.match($('#main').innerHTML,/id="rework" disabled/,'Reviewed version is read-only');
rerender();assert.match($('#main').innerHTML,/value="old" selected/,'Selection survives rerender');
A.project={id:'q',name:'Project Q'};rerender();
assert.match($('#main').innerHTML,/value="other" selected/,'Project change chooses its own version');
assert(!$('#main').innerHTML.includes('value="old"'));
$('#pass').onclick();modal.submit();assert.equal(reviewed[1],'other','Action targets selected version');
console.log('PASS TASK16: pending default, scoped selector, retained selection, project switch, selected action target, read-only controls, invalid action rollback (DOM stub).');
