/* Lớp dữ liệu: tất cả thay đổi được kiểm tra rồi lưu một lần vào LocalStorage. */
window.Store = (() => {
  const KEY='creatorstudio.sv3.v1'; let db;
  const clone=x=>JSON.parse(JSON.stringify(x));
  const requireValue=(test,message)=>{if(!test)throw new Error(message)};
  const roles=['Client','Designer','Lead','Admin'], statuses=['todo','doing','review','done'];
  function load(){const raw=localStorage.getItem(KEY);db=raw?JSON.parse(raw):CS_SEED();requireValue(db.schema===1&&['users','projects','tasks','briefs','versions','notes','comments','proposals','tags','activity'].every(k=>Array.isArray(db[k]))&&db.settings,'Dữ liệu lưu không hợp lệ. Hãy xuất bản sao rồi đặt lại dữ liệu mẫu.');if(!raw)localStorage.setItem(KEY,JSON.stringify(db));return clone(db)}
  const get=()=>clone(db);
  const id=prefix=>prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
  function tx(fn){const latest=localStorage.getItem(KEY);if(latest){const stored=JSON.parse(latest);requireValue(stored.schema===1,"Dữ liệu đã thay đổi định dạng. Hãy tải lại trang.");db=stored}const next=clone(db);fn(next);try{localStorage.setItem(KEY,JSON.stringify(next))}catch(e){throw new Error('Không lưu được dữ liệu. Bộ nhớ trình duyệt có thể đã đầy hoặc bị chặn. Thay đổi chưa được áp dụng.')}db=next;return get()}
  function actor(d,uid,role){const u=d.users.find(u=>u.id===uid);requireValue(u&&u.active&&u.role===role,'Bạn không có quyền thực hiện thao tác này.');return u}
  function writable(d,pid){const p=d.projects.find(p=>p.id===pid);requireValue(p,'Không tìm thấy dự án.');requireValue(!p.archived,'Dự án đã lưu trữ, chỉ được xem.');return p}
  function log(d,text){d.activity.unshift({id:id('a'),text,time:new Date().toISOString()});d.activity=d.activity.slice(0,80)}
  function taskData(d,t){requireValue(t.title?.trim().length>=3&&t.title.trim().length<=120,'Tên công việc cần từ 3 đến 120 ký tự.');requireValue(statuses.includes(t.status),'Trạng thái không hợp lệ.');requireValue(['high','medium','low'].includes(t.priority),'Mức ưu tiên không hợp lệ.');requireValue(d.users.some(u=>u.id===t.assignee&&u.active&&['Lead','Designer'].includes(u.role)),'Chọn người phụ trách đang hoạt động.');requireValue(/^\d{4}-\d{2}-\d{2}$/.test(t.due)&&!isNaN(Date.parse(t.due))&&new Date(t.due+'T00:00:00Z').toISOString().slice(0,10)===t.due,'Chọn hạn hoàn thành.');return {...t,title:t.title.trim(),description:(t.description||'').trim()}}
  function saveTask(uid,data){let result;tx(d=>{actor(d,uid,'Lead');writable(d,data.projectId);const clean=taskData(d,data);if(data.id){const t=d.tasks.find(t=>t.id===data.id&&t.projectId===data.projectId);requireValue(t,'Không tìm thấy công việc.');Object.assign(t,clean);result=t.id}else{result=id('CS');d.tasks.push({...clean,id:result,type:clean.type||'Công việc'})}log(d,'Đã lưu công việc: '+clean.title)});return result}
  function moveTask(uid,tid,status){tx(d=>{actor(d,uid,'Lead');const t=d.tasks.find(t=>t.id===tid);requireValue(t,'Không tìm thấy công việc.');writable(d,t.projectId);requireValue(statuses.includes(status),'Trạng thái không hợp lệ.');t.status=status;log(d,'Đã đổi trạng thái: '+t.title)})}
  function brief(uid,bid,action,data){tx(d=>{actor(d,uid,'Lead');const b=d.briefs.find(b=>b.id===bid);requireValue(b,'Không tìm thấy brief.');writable(d,b.projectId);requireValue(b.status==='submitted','Brief này đã được xử lý.');if(action==='return'){requireValue(data.reason?.trim().length>=8,'Nêu lý do cần bổ sung, ít nhất 8 ký tự.');b.status='changes';b.reason=data.reason.trim()}else{const task=taskData(d,{...data,projectId:b.projectId,status:'todo'});b.status='approved';d.tasks.push({...task,id:id('CS'),briefId:bid,type:'Từ brief'})}log(d,(action==='return'?'Đã yêu cầu bổ sung brief: ':'Đã duyệt brief và tạo việc: ')+b.title)})}
  function note(uid,vid,data){tx(d=>{actor(d,uid,'Lead');const v=d.versions.find(v=>v.id===vid);requireValue(v,'Không tìm thấy phiên bản.');writable(d,v.projectId);requireValue(v.status==='Internal Review','Phiên bản không còn ở bước duyệt nội bộ.');requireValue(data.text?.trim().length>=3&&data.text.length<=600,'Ghi chú cần từ 3 đến 600 ký tự.');if(data.id){const n=d.notes.find(n=>n.id===data.id&&n.versionId===vid);requireValue(n,'Không tìm thấy ghi chú.');n.text=data.text.trim()}else d.notes.push({id:id('n'),versionId:vid,text:data.text.trim(),x:Math.max(2,Math.min(98,Number(data.x)||50)),y:Math.max(2,Math.min(98,Number(data.y)||50)),resolved:false});log(d,'Đã lưu ghi chú nội bộ.')})}
  function resolveNote(uid,nid){tx(d=>{actor(d,uid,'Lead');const n=d.notes.find(n=>n.id===nid);requireValue(n,'Không tìm thấy ghi chú.');const v=d.versions.find(v=>v.id===n.versionId);writable(d,v.projectId);requireValue(v.status==='Internal Review','Phiên bản đã chuyển bước.');n.resolved=!n.resolved})}
  function reviewChecks(uid,vid,brand,info){tx(d=>{actor(d,uid,'Lead');const v=d.versions.find(v=>v.id===vid);requireValue(v,'Không tìm thấy phiên bản.');writable(d,v.projectId);requireValue(v.status==='Internal Review','Phiên bản đã chuyển bước.');v.checkBrand=!!brand;v.checkInfo=!!info})}
  function review(uid,vid,action,reason=''){tx(d=>{actor(d,uid,'Lead');requireValue(['pass','rework'].includes(action),'Thao tác duyệt không hợp lệ.');const v=d.versions.find(v=>v.id===vid);requireValue(v,'Không tìm thấy phiên bản.');writable(d,v.projectId);requireValue(v.status==='Internal Review','Phiên bản đã được xử lý.');if(action==='pass'){requireValue(v.checkBrand&&v.checkInfo,'Hoàn thành checklist trước khi gửi.');requireValue(!d.notes.some(n=>n.versionId===vid&&!n.resolved),'Còn ghi chú nội bộ chưa xử lý.');v.status='Client Review'}else{requireValue(reason.trim().length>=8,'Nhập lý do yêu cầu sửa, ít nhất 8 ký tự.');v.status='Changes Requested'}v.history.push({action,reason,time:new Date().toISOString()});log(d,action==='pass'?'Đã chuyển phiên bản sang Client Review.':'Đã yêu cầu Designer sửa phiên bản.')})}
  function addComment(uid,pid,vid,text){tx(d=>{actor(d,uid,'Lead');writable(d,pid);requireValue(d.versions.some(v=>v.id===vid&&v.projectId===pid),'Phiên bản không hợp lệ.');requireValue(text.trim().length>=5&&text.length<=1000,'Phản hồi cần từ 5 đến 1.000 ký tự.');d.comments.push({id:id('C'),projectId:pid,versionId:vid,author:'Phản hồi nhập thủ công',text:text.trim()})})}
  function proposals(uid,pid,items){tx(d=>{actor(d,uid,'Lead');writable(d,pid);const pending=d.proposals.filter(p=>p.projectId===pid&&!p.taskId);requireValue(!pending.length,'Hãy xử lý hoặc bỏ các đề xuất cũ trước khi tạo lại.');for(const item of items){requireValue(!d.tasks.some(t=>t.projectId===pid&&t.sourceIds?.some(s=>item.sourceIds.includes(s))),'Phản hồi này đã có công việc. Bỏ chọn phản hồi đã xử lý trước khi tạo lại.');d.proposals.push({...item,id:id('ai'),projectId:pid,taskId:null})}log(d,'Đã tạo '+items.length+' gợi ý AI mô phỏng.')})}
  function saveProposal(uid,aid,data){tx(d=>{actor(d,uid,'Lead');const a=d.proposals.find(a=>a.id===aid);requireValue(a&&!a.taskId,'Đề xuất không còn chỉnh sửa được.');writable(d,a.projectId);const task=taskData(d,{...a,...data,status:'todo'});Object.assign(a,{title:task.title,description:task.description,assignee:task.assignee,priority:task.priority,due:task.due,ambiguous:false});log(d,'Đã chỉnh sửa đề xuất AI.')})}
  function removeProposal(uid,aid){tx(d=>{actor(d,uid,'Lead');const a=d.proposals.find(a=>a.id===aid);requireValue(a&&!a.taskId,'Không thể bỏ đề xuất đã tạo công việc.');writable(d,a.projectId);d.proposals=d.proposals.filter(a=>a.id!==aid)})}
  function discard(uid,pid){tx(d=>{actor(d,uid,'Lead');writable(d,pid);d.proposals=d.proposals.filter(a=>a.projectId!==pid||a.taskId)})}
  function convert(uid,pid,ids){tx(d=>{actor(d,uid,'Lead');writable(d,pid);requireValue(ids.length,'Chọn ít nhất một đề xuất.');for(const aid of [...new Set(ids)]){const a=d.proposals.find(a=>a.id===aid&&a.projectId===pid);requireValue(a&&!a.taskId,'Đề xuất đã được chuyển hoặc không tồn tại.');requireValue(!a.ambiguous,'Cần làm rõ phản hồi mơ hồ trước khi tạo việc.');const t=taskData(d,{...a,status:'todo'});const tid=id('CS');d.tasks.push({id:tid,projectId:pid,title:t.title,description:t.description,assignee:t.assignee,priority:t.priority,status:'todo',due:t.due,type:'Từ phản hồi',sourceIds:a.sourceIds,proposalId:aid});a.taskId=tid}log(d,'Đã chuyển '+ids.length+' đề xuất thành công việc.')})}
  function saveUser(uid,data){tx(d=>{actor(d,uid,'Admin');requireValue(data.name?.trim().length>=2&&data.name.length<=80,'Tên cần từ 2 đến 80 ký tự.');const email=data.email?.trim().toLowerCase();requireValue(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email),'Email không hợp lệ.');requireValue(!d.users.some(u=>u.id!==data.id&&u.email.toLowerCase()===email),'Email này đã tồn tại.');requireValue(roles.includes(data.role),'Vai trò không hợp lệ.');if(data.id){const u=d.users.find(u=>u.id===data.id);requireValue(u,'Không tìm thấy người dùng.');requireValue(data.id!==uid||data.role===u.role,'Không thể tự đổi vai trò của phiên demo đang dùng.');if(u.role==='Admin'&&data.role!=='Admin')requireValue(d.users.some(x=>x.id!==u.id&&x.role==='Admin'&&x.active),'Cần giữ ít nhất một Admin hoạt động.');Object.assign(u,{name:data.name.trim(),email,role:data.role})}else d.users.push({id:id('u'),name:data.name.trim(),email,role:data.role,active:true});log(d,'Đã lưu người dùng: '+data.name.trim())})}
  function toggleUser(uid,id){tx(d=>{actor(d,uid,'Admin');const u=d.users.find(u=>u.id===id);requireValue(u,'Không tìm thấy người dùng.');requireValue(id!==uid,'Không thể tự khóa tài khoản đang dùng.');if(u.active&&u.role==='Admin')requireValue(d.users.some(x=>x.id!==id&&x.active&&x.role==='Admin'),'Cần giữ ít nhất một Admin hoạt động.');u.active=!u.active;log(d,(u.active?'Đã mở khóa: ':'Đã khóa: ')+u.name)})}
  function settings(uid,data){tx(d=>{actor(d,uid,'Admin');const n=Number(data.warningDays);requireValue(Number.isInteger(n)&&n>=0&&n<=30,'Ngưỡng cảnh báo phải từ 0 đến 30 ngày.');requireValue(data.versionPattern.length<=100&&['{project}','{asset}','{number}'].every(s=>data.versionPattern.includes(s)),'Mẫu cần đủ {project}, {asset} và {number}.');d.settings={warningDays:n,versionPattern:data.versionPattern.trim(),requireReview:!!data.requireReview};log(d,'Đã lưu quy tắc studio.')})}
  function tag(uid,name,action,newName){tx(d=>{actor(d,uid,'Admin');if(action==='delete'){requireValue(!d.projects.some(p=>p.tags.includes(name)),'Nhãn đang được dự án sử dụng.');d.tags=d.tags.filter(t=>t!==name)}else{const label=(newName||name).trim();requireValue(label.length>=2&&label.length<=30,'Nhãn cần từ 2 đến 30 ký tự.');requireValue(!d.tags.some(t=>t.toLowerCase()===label.toLowerCase()&&!(action==='edit'&&t===name)),'Nhãn đã tồn tại.');if(action==='edit'){requireValue(d.tags.includes(name),'Nhãn không tồn tại.');requireValue(!d.projects.some(p=>p.archived&&p.tags.includes(name)),'Nhãn thuộc dự án đã lưu trữ, không thể đổi.');d.tags=d.tags.map(t=>t===name?label:t);d.projects.forEach(p=>p.tags=p.tags.map(t=>t===name?label:t))}else d.tags.push(label)}log(d,'Đã cập nhật danh mục nhãn.')})}
  function archive(uid,pid){tx(d=>{actor(d,uid,'Admin');const p=writable(d,pid);requireValue(!d.tasks.some(t=>t.projectId===pid&&t.status!=='done'),'Còn công việc chưa hoàn thành.');requireValue(!d.briefs.some(b=>b.projectId===pid&&b.status!=='approved'),'Còn brief chưa được duyệt.');requireValue(!d.versions.some(v=>v.projectId===pid&&v.status!=='Approved'),'Còn phiên bản chưa được khách hàng duyệt.');p.archived=true;log(d,'Đã lưu trữ dự án: '+p.name)})}
  function reset(){const next=CS_SEED();localStorage.setItem(KEY,JSON.stringify(next));db=next}
  return {KEY,load,get,id,saveTask,moveTask,brief,note,resolveNote,reviewChecks,review,addComment,proposals,saveProposal,removeProposal,discard,convert,saveUser,toggleUser,settings,tag,archive,reset};
})();
